### ISSUE TITLE
Mac version using mpkg, but package appears not to be?

### ISSUE THREAD

**Issue by noahgibbs** [jtimberman/virtualbox-cookbook#3]
Right now, the Mac OS X default recipe is downloading the dmg successfully, but looking for the file /Volumes/VirtualBox/VirtualBox.mpkg and failing -- there's a file /Volumes/VirtualBox/VirtualBox.pkg, but no mpkg.

I assume this is as simple as "change the type to pkg".

The download links to a bunch of old versions of VirtualBox just changed. Maybe Oracle did something unfortunate and changed their minds about format or something?

**Comment by noahgibbs** [comment]
If I change the virtualbox cookbook to use 'pkg' instead of 'mpkg' type it seems to work for me (see http://github.com/noahgibbs/virtualbox-cookbook for the trivial change). I don't know if there are old archives still using mpkg, though :-(

**Comment by jtimberman** [comment]
Dunno TBH, I'm not using Virtualbox anymore. The [supermarket cookbook](https://supermarket.chef.io/cookbooks/virtualbox) repository is [here](https://github.com/bradleyd/virtualbox-cookbook).
